// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAer_M93kh47KTC1YIPyjxtz6q-cd5JjSc',
    appId: '1:226172390394:web:66dba704bd93553304f243',
    messagingSenderId: '226172390394',
    projectId: 'pocketbizz-mobile',
    authDomain: 'pocketbizz-mobile.firebaseapp.com',
    storageBucket: 'pocketbizz-mobile.firebasestorage.app',
    measurementId: 'G-5EQDVS2DJ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJgYBiwIyVGA49fB4jg76OgRyH1AeTDKI',
    appId: '1:226172390394:android:a4c8b7c11994da2704f243',
    messagingSenderId: '226172390394',
    projectId: 'pocketbizz-mobile',
    storageBucket: 'pocketbizz-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfXDbYoKt0xtNNBlGQ7FtbNCA6p1sSD6M',
    appId: '1:226172390394:ios:53d792bd3d2f0bb704f243',
    messagingSenderId: '226172390394',
    projectId: 'pocketbizz-mobile',
    storageBucket: 'pocketbizz-mobile.firebasestorage.app',
    iosBundleId: 'com.example.pocketbizzMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfXDbYoKt0xtNNBlGQ7FtbNCA6p1sSD6M',
    appId: '1:226172390394:ios:53d792bd3d2f0bb704f243',
    messagingSenderId: '226172390394',
    projectId: 'pocketbizz-mobile',
    storageBucket: 'pocketbizz-mobile.firebasestorage.app',
    iosBundleId: 'com.example.pocketbizzMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAer_M93kh47KTC1YIPyjxtz6q-cd5JjSc',
    appId: '1:226172390394:web:b0b98c5a7ca4a50704f243',
    messagingSenderId: '226172390394',
    projectId: 'pocketbizz-mobile',
    authDomain: 'pocketbizz-mobile.firebaseapp.com',
    storageBucket: 'pocketbizz-mobile.firebasestorage.app',
    measurementId: 'G-MGTX526WLB',
  );
}
